include:
  - project: 'broeskamp/devops/gitlab/gitlab-ci'
    ref: main
    file:
      - '/workflow/workflow.yaml'
      - '/versions/docker-build-container.yaml'

default:
  image: registry.gitlab.com/broeskamp/devops/gitlab/docker-build-container/amazoncorretto:${CORRETTO_VERSION}

variables:
  CORRETTO_JDK_VERSION: 25

stages:
  - build
  - test
  - native

maven:build:
  stage: build
  script:
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/classes/
      - target/test-classes/
      - target/quarkus-app/
      - target/floci-*.jar
      - target/quarkus-artifact.properties

maven:test:
  stage: test
  script:
    - ./mvnw surefire:test
  artifacts:
    when: always
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml
    paths:
    - target/surefire-reports/

maven:native:
  stage: native
  image: registry.gitlab.com/broeskamp/devops/gitlab/docker-build-container/amazoncorretto-docker:${CORRETTO_VERSION}
  parallel:
    matrix:
      - RUNNER_TAG: [linux, arm]
  tags:
    - $RUNNER_TAG
  script:
    - |
      set --
      if [ "$RUNNER_TAG" = "linux" ]; then
        set -- -Dquarkus.native.additional-build-args-append=-march=x86-64-v2
      fi
      ./mvnw package \
        -Dnative \
        -Dmaven.compiler.release=25 \
        -Dmaven.main.skip=true \
        -Dmaven.test.skip=true \
        -Dmaven.resources.skip=true \
        -Dquarkus.generate-code.skip=true \
        -Dquarkus.native.remote-container-build=true \
        -Dquarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25 \
        "$@"
  artifacts:
    expire_in: 1 day
    paths:
      - target/*-runner
      - target/*.properties
      - target/*.so
